
### 
POST http://localhost:4000/api/site
Content-Type: application/json

{
    "siteName": "UNREGID",
    "siteAddress": "Pickering",
    "siteContactNumber": "0784591495",
    "siteNote": "ina gandagi"
}
####
POST http://localhost:4000/api/siteName 
Content-Type: application/json

{
    "siteName":"UNREGID"
}
### 

POST http://localhost:4000/api/hardwaretoapp
Content-Type: application/json

{
    "recordID": "6244190577e06ddfac515e0a",
    "data": {
        "location":"london",
        "type":"server",
        "MakeModel": "yahoo",
        "ServiceTagSerialNo": "SN45sdfFd546",
        "CPU":"Core",
        "RAM": "2",
        "HDD": "4",
        "Graphic": "1",
        "DVDDrive": "Beats",
        "PowerSupply": "electrons",
        "sourceFile":"D:/mainsources",
        "PowerSettoNever": false,
        "RaidLevel" :"2", 
         "OS": {
        "OSname": "linux",
        "OSVersion": "ubuntu",
        "UserName": "sa",
        "password":"mingo",
        "UpdateInstalled": "yes",
        "UpdateTurnedOff": false
        },
    "apps": {
        "appsName" : "ccure",
        "appsVersion" : "4" ,
        "appsUserName":"man",
        "appsPassword":"man"
    },
    "DB":{
        "DBinstalled": false,
        "DBname": "mongdb",
        "DBVersion": "lastest",
        "DBsaPassword": "jan"
    },      
    "network":{
        "IP": "192.18.10.25",
        "subnetMask": "255.0.0.0",
        "gateway": "8.8.8.8"
    }
    }
}
####
GET http://localhost:4000/api/allrecords HTTP/1.1